version: '3'
services:
  redis:
    image: redis
    command: redis-server --requirepass eews2024zat1234XyZ
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

  eews-mongo:
    image: mongo:latest
    container_name: eews-mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'

  seeder:
    image: pragusga/eews:seeder
    container_name: seeder
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eews2024zat1234XyZ

volumes:
  redis_data:
  mongodb_data:
