version: '3'
services:
  eews-mongo:
    image: mongo:latest
    container_name: eews-mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=<database_name>
      - MONGO_INITDB_ROOT_USERNAME=<user>
      - MONGO_INITDB_ROOT_PASSWORD=<pass>

volumes:
  mongodb_data:
