version: '3'
services:
  redis:
    image: redis
    command: redis-server --requirepass eews2024zat1234XyZ
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  redis_data:
